name:                TLT
version:             0.1.0.0
github:              "jphmrst/TLT"
license:             LGPL-3
author:              "John Maraist"
maintainer:          "haskell-tlt@maraist.org"
copyright:           "2022 John Maraist"
category:	     Test
synopsis:	     "Testing focused on computations in monad transformers."
description:	     "A small unit test system oriented with an emphasis on examining intermediate results of computations in monad transformers.  The Test.TLT Haddock page is the main piece of documentation; or see also the GitHub repository <https://github.com/jphmrst/TLT/>."

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - HUnit >= 1.6.2.0 && < 1.7   # https://hackage.haskell.org/package/HUnit
  - symbol >= 0.2.4 && < 0.3    # https://hackage.haskell.org/package/symbol
  - transformers >= 0.5.6.2 && < 0.6   # https://hackage.haskell.org/package/transformers
  - ansi-terminal >= 0.11.1 && < 0.12  # https://hackage.haskell.org/package/ansi-terminal
  - STMonadTrans >= 0.4.6
  - either >= 5.0 && < 5.1 # https://hackage.haskell.org/package/either-4.4.1
  - resourcet >= 1.2 && < 1.3 # 
  - free >= 5.1 && < 5.2 # 

executables:
  TLT-exe:
    main:                Failing.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TLT

tests:
  TLT-test-fail:
    main:                Passing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TLT
    - mtl
    - transformers >= 0.5.6.2 && < 0.6   # https://hackage.haskell.org/package/transformers
