name:           TLT
version:        0.5.0.1
github:         "jphmrst/TLT"
license:        LGPL-3
author:         "John Maraist"
maintainer:     "haskell-tlt@maraist.org"
copyright:      "2022,2023 John Maraist"
category:       Test
synopsis:       "Testing in monads and transformers without standalone static specs"
description:    "A quick-and-dirty unit test system without test specifications, motivated by easy examination of intermediate results of computations in monad transformers.  See the GitHub repository <https://github.com/jphmrst/TLT/> for documentation, or the Haddock page for additional examples."

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base          (>= 4.14.1 && < 4.15) || (>= 4.15.1 && < 4.16) || (>= 4.16.0 && < 4.17) || (>= 4.17.0 && < 4.18) || (>= 4.18.0 && < 4.19)
- transformers  (>= 0.5.6  && < 0.6) || (>= 0.6.1  && < 0.7)
- ansi-terminal >= 0.11.1 && < 0.12
- STMonadTrans  >= 0.4.6  && < 0.5
- resourcet     (>= 1.2.4  && < 1.3) || (>= 1.3.0  && < 1.4)
- free          >= 5.1.7  && < 5.2
- mtl           >= 2.2.2  && < 2.3
- exceptions    >= 0.10.0  && < 0.11

library:
  source-dirs: src

executables:
  TLT-exe:
    main:                Failing.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TLT

tests:
  TLT-test-fail:
    main:                Passing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TLT
